import { StyleSheet } from "react-native";

const registrationScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  camera: {
    flex: 1,
  },
  overlay: {
    flex: 1,
    backgroundColor: "transparent",
    justifyContent: "space-between",
    padding: 20,
    paddingTop: 60,
    paddingBottom: 40,
  },
  instructionBox: {
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  faceFrame: {
    position: "absolute",
    top: "50%",
    left: "50%",
    width: 250,
    height: 300,
    marginLeft: -125,
    marginTop: -150,
    borderWidth: 3,
    borderColor: "#4ade80",
    borderRadius: 150,
    backgroundColor: "transparent",
    shadowColor: "#4ade80",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: 10,
  },
  progressIndicators: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
  },
  progressDot: {
    height: 12,
    borderRadius: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  progressDotActive: {
    backgroundColor: "#4ade80",
    shadowColor: "#4ade80",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 8,
    elevation: 5,
  },
  controls: {
    backgroundColor: "#fff",
    padding: 20,
    paddingBottom: 30,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  buttonGroup: {
    flexDirection: "row",
    gap: 12,
  },
  helpText: {
    textAlign: "left",
    opacity: 0.7,
  },
  progressCounter: {
    marginTop: 8,
    fontSize: 12,
    opacity: 0.8,
  },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
    backgroundColor: "#fff",
  },
  permissionText: {
    textAlign: "center",
    maxWidth: 300,
  },
});

export default registrationScreenStyles;
